Add my impression
jpub-gh/first-pr pull request #139
Opened 2017-05-22 12:46 UTC by danbi2990

__Thank you.__

2023-09-18 02:47 UTC, ryush00 requested changes

2023-09-18 02:47 UTC, ryush00 commented on index.html
> +	          <p class="impression">감사합니다.</p>
불필요한 TAB 문자열이 들어가 있습니다. 스페이스로 바꿔주시면 감사하겠습니다.

2024-09-09 10:00 UTC, danbi2990 commented on index.html
> +	          <p class="impression">감사합니다.</p>
TAB => 스페이스 변경했습니다.
덕분에 현역 개발자로 일하고 있습니다. 감사합니다.

2024-09-09 10:03 UTC, ryush00 approved these changes
LGTM! 👍

2025-02-24 04:40 UTC, closed without merging